after_success:
  - "java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml"
before_install:
  - "sudo apt-get install jq"
  - "wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)"
before_script: "cd backend"
dist: trusty
jdk: openjdk8
language: java
